name: URL Builder

on:
  push:
    paths:
      - 'builder/*'
  pull_request:
    paths:
      - 'builder/*'
  workflow_dispatch: ~

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Build
        working-directory: builder
        run: |
          yarn install
          yarn build
